event:
  name: "National Social Summit 2019"
  url: "http://www.nationalsocialsummit.org/"
site:
  lang: "en"
  title: "Certificates for National Social Summit 2019"
  eventLogo: "static/images/event_logo.png"
  index:
    message: "Please enter your REGISTERED ID"
    emailPlaceholder: "Will be 7 digit id"
    inputLabel: "Email"
    submit: "Generate"
certificate:
  eventLogo: "static/images/event_logo.png"
  iitrLogo: "static/images/iitr_logo.png"
  nssLogo: "static/images/nss_logo.png"
  signature1 : "static/images/Nishank.png"
  signature2 : "static/images/Yash.png"
  background: "static/images/background.png"
  divider: "static/images/divider.png"
  header: "CERTIFICATE"
  type1: "OF PARTICIPATION"
  textLine1: "National Service Scheme, IIT Roorkee recognises and appreciates the participation of"
  textLine2: "during the National Social Summit held between February 8th - 10th 2019."
routes:
  certificate: certificate
errors:
  error: "<strong>Error:</strong> %message%"
  missingEmail: "Missing email address!"
  invalidEmail: "Invalid email address!"
  emailNoExists: "The email address does not exists!"
  missingId: "Missing id address!"
  invalidId: "Invalid id address!"
  idNoExists: "The id does not exists!"
  notAttended: "You did not attended to this Summit!"
  csvError: "An error occurred while reading the CSV file!"
  csrfError: "Cheatin' huh?"
  error404: "404: Page not Found"
  error500: "500: Internal Server Error"
csv: csv/sample.csv